"""add_settlement_handover_table

Revision ID: befa64175889
Revises: 08e53341e9eb
Create Date: 2026-06-15 12:02:04.641899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befa64175889'
down_revision: Union[str, None] = '08e53341e9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_handovers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('admin_name', sa.String(length=200), nullable=False),
    sa.Column('driver_name', sa.String(length=200), nullable=False),
    sa.Column('signature_admin_url', sa.Text(), nullable=True),
    sa.Column('signature_driver_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_handovers')
    # ### end Alembic commands ###
